-- Patch: correct users.personality_embedding to vector(1024).
--
-- EMBEDDING_MODEL is mxbai-embed-large (1024 dims) and schema_initializer.sql declares
-- vector(1024), but some DB volumes were initialized with vector(1536) (the earlier
-- OpenAI dimension) and never migrated. That mismatch made EVERY embedding write fail
-- ("expected 1536 dimensions, not 1024"), so no user ever got a personality_embedding
-- and squad matchmaking silently returned zero matches for everyone.
--
-- Embeddings are regenerated by the background worker, so discarding existing values is
-- safe. The ivfflat index is dropped and recreated for the new dimension. Re-queues all
-- users so the worker regenerates embeddings once a provider is reachable.

DROP INDEX IF EXISTS idx_users_embedding;

ALTER TABLE users
  ALTER COLUMN personality_embedding TYPE vector(1024) USING NULL;

UPDATE users
SET pending_embeddings = TRUE,
    embedding_attempts = 0,
    embedding_next_attempt_at = NULL
WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_users_embedding
  ON users USING ivfflat (personality_embedding vector_cosine_ops) WITH (lists = 100);
